name: Update GitHub Stats Images

# 🚀 Este workflow só roda manualmentee
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick curl

            - name: Baixar SVGs da sua instância
        run: |
          mkdir -p assets/github-stats

          USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

          echo "Baixando estatísticas..."
          curl -f -L -A "$USER_AGENT" "https://github-readme-stats-git-master-vitor-de-castro-mendes-projects.vercel.app/api?username=Vitorcmendes&show_icons=true&theme=dracula&count_private=true" -o assets/github-stats/stats.svg || (echo "Falha ao baixar stats.svg" && exit 1)

          echo "Baixando linguagens..."
          curl -f -L -A "$USER_AGENT" "https://github-readme-stats-git-master-vitor-de-castro-mendes-projects.vercel.app/api/top-langs/?username=Vitorcmendes&layout=compact&langs_count=6&theme=dracula" -o assets/github-stats/langs.svg || (echo "Falha ao baixar langs.svg" && exit 1)

          echo "Prévia do arquivo stats.svg:"
          head -n 5 assets/github-stats/stats.svg

      - name: Converter SVG para PNG
        run: |
          convert -background none assets/github-stats/stats.svg assets/github-stats/stats.png
          convert -background none assets/github-stats/langs.svg assets/github-stats/langs.png

      - name: Verificar se houve mudança nas imagens
        id: check_changes
        run: |
          git add assets/github-stats/*.png
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Fazer commit e push se mudou
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -m "Atualizar imagens do GitHub Stats [bot]"
          git push

